### ISSUE TITLE
Files won't save

### ISSUE THREAD

**Issue by koolkreate** [soopercool101/BrawlCrate#2]
So previously, i was able to edit mkwii files no errors; however as of 4th November, an error occurs "Object reference not set
![image](https://user-images.githubusercontent.com/57417014/68245062-1af49480-000e-11ea-87b9-f9ec527ced66.png)
 to instance of an object" Could you please fix... I'll revert to the older versions for now.

**Comment by soopercool101** [comment]
Could you please leave the brres you are editing here or send it to me via discord?

**Comment by koolkreate** [comment]
[desert_course.zip](https://github.com/soopercool101/BrawlCrate/files/3821254/desert_course.zip)
