### ISSUE TITLE
won't start up

### ISSUE THREAD

**Issue by commanderdarkkirby** [soopercool101/BrawlCrate#21]
so, i'm visual studio 2017 to try and start up the program but i keep getting a message about some missing debug profile or something.

**Comment by soopercool101** [comment]
Make sure you have all the requirements listed here: https://www.github.com/soopercool101/BrawlCrate/tree/master/CONTRIBUTING.md

**Comment by commanderdarkkirby** [comment]
still having the same issue. i installed everything listed in the requirements, and i still, get the same messaged when trying to run the program with visual studio.
