### ISSUE TITLE
Texture importing includes .tex0 extension

### ISSUE THREAD

**Issue by Kevinn1109** [soopercool101/BrawlCrate#22]
When mass-importing tex0 files to a brres archive, the tool includes the tex0 extension in the name of all textures. This is unwanted behaviour, as they will have to be fixed manually, which takes a lot of time.

The alternative, importing textures without extension, makes a window pop-up to re-encode the textures, which is unwanted as well.

It would be great if the extension of imported files is discarded in the names inside the brres.

**Comment by soopercool101** [comment]
What method are you using to mass-import these textures? Because I'm not running into such an issue on my end.

Mass-import using multiselect:
https://gfycat.com/AdolescentSoggyEasteuropeanshepherd

Mass-import from folder:
https://gfycat.com/AnguishedConcreteBeaver
