### ISSUE TITLE
Imported the .anim file from the 3DS Game and the Error Occurred

### ISSUE THREAD

**Issue by P0W3** [soopercool101/BrawlCrate#27]
I put the .anim file from the 3DS game (Pokemon - Ultra Sun), and this happened.

![image](https://user-images.githubusercontent.com/18279115/111023460-2a74b200-83a7-11eb-82ce-4c4046b69c67.png)

When I created the new BRRES file, and I imported the .anim file from the 3DS game (Pokemon - Ultra Sun), this error happened.

![image](https://user-images.githubusercontent.com/18279115/111023515-76275b80-83a7-11eb-8f05-70c0f6d22d6e.png)

I use Windows (64-bit) (v10.0.19041.804).

**Comment by soopercool101** [comment]
Only Maya format anim files are accepted. The errors you've gotten point towards the file not being in the Maya anim format. Send the file here if you want me to confirm this.

**Comment by P0W3** [comment]
Here is the .anim file.

[Fight_attack.zip](https://github.com/soopercool101/BrawlCrate/files/6136195/Fight_attack.zip)

**Comment by soopercool101** [comment]
Yeah that's unity format anim, which is not supported by the program. You'll need to convert it to the maya format via either Maya or Blender
