### ISSUE TITLE
Problems with Textures on some Models

### ISSUE THREAD

**Issue by DormNes** [soopercool101/BrawlCrate#29]
**Describe the bug**
I open up brawlcrate, everything seems to be in working order, I open any Wario models, I open him in advanced editor and he looks like in the screenshots. Most models works aside from Project M waluigi. Clicking on the texture tab aka the metal texture and turning it off. All of the tetxures aren't there.

**To Reproduce**
1. Literally open brawlcrate
2. Get Wario or Project M Waluigi and custom models of Wario
3. Advanced Editor
4. Problem

**Expected behavior**
I expected the textures to APPEAR!

**Screenshots**

![WAHHHH](https://user-images.githubusercontent.com/60552763/111785004-71284780-8892-11eb-9081-1481a416b90f.png)
![tophatWAH](https://user-images.githubusercontent.com/60552763/111785036-79808280-8892-11eb-9fd5-d49582c36ae1.png)
![ProjectWAH](https://user-images.githubusercontent.com/60552763/111785053-7daca000-8892-11eb-9a7c-7fe9d88c8a91.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Literally i re updated it to the newest verison aka v0.36b

**Crash Log**
If there was a crash report, please submit it and include a link to the relevant issue from [BrawlCrateIssues](https://github.com/BrawlCrate/BrawlCrateIssues/issues).

**Additional context**

Please attach any relevant files you were working on.

**Comment by soopercool101** [comment]
Press the M key to toggle Metal View, or go to View > Models > Metal and ensure it's unchecked
![sOIbfJDSkk](https://user-images.githubusercontent.com/35675593/111792325-61543780-8881-11eb-8150-a81b709182ea.gif)

**Comment by DormNes** [comment]
Ugh, I feel dumb now. Thank you so much though.

**Comment by soopercool101** [comment]
No worries, it's a fairly common issue, I'll probably make it a more difficult to accidentally activate hotkey in the future.
