### ISSUE TITLE
Not able to handle large BRSAR's

### ISSUE THREAD

**Issue by BlueSupernova22** [soopercool101/BrawlCrate#3]
Hi I'm new here and i decided to bring up this issue to you since you created this and I thought this might give you some idea but I've had this issue since BrawlBox and I thought maybe you can help me out but I have been using BrawlCrate and BrawlBox to modify the DanceDanceRevolution BRSAR files Since that is where the music is injected and used the replace sound option. After replacing and trying to save I get this
https://imgur.com/57kbYLx
I assume it is not able to handle the large amount of process

As for DanceDanceRevolution II BRSAR it will not open at all, I'm guessing due to it's large filesize
https://imgur.com/zboTeGB

**Comment by soopercool101** [comment]
Use the experimental AnyCPU build in the canary release. This will allow you to use more RAM if you are on a 64-bit OS
