### ISSUE TITLE
The White Image Stuff Appear on a PMD Stage Model in BrawlCrate (v0.37)

### ISSUE THREAD

**Issue by P0W3** [soopercool101/BrawlCrate#34]
I use BrawlCrate (v0.37).

The shaders are off, because I am not using any shaders.

![image](https://user-images.githubusercontent.com/18279115/135698251-86f98872-16c3-4eae-9032-227da40e7ac6.png)

I imported a PMD stage model, and this is what it looks like.

![image](https://user-images.githubusercontent.com/18279115/135697885-52b1b65c-f34c-4afe-a5c8-cce9fa2e776e.png)

The whole stage model that I am looking at does not look right. The errors that I am seeing is the white image stuff that gets in the way.

I use Microsoft Windows (Version 10.0.19043.1237).

![image](https://user-images.githubusercontent.com/18279115/135698113-0de81930-66c2-4d4f-b0e9-a79f10117078.png)

**Comment by soopercool101** [comment]
You need shaders to see transparency
