### ISSUE TITLE
System.OutOfMemoryException on trying to load a large brsar file

### ISSUE THREAD

**Issue by red031000** [soopercool101/BrawlCrate#4]
**Describe the bug**
A System.OutOfMemoryException occurs while trying to load a large (340mb) brsar file (tested on Pokemon Battle Revolution PAL's pbr_sound.brsar)

**To Reproduce**
1. Download BrawlCrate latest
2. Open a large brsar file
3. OutOfMemoryException pops up, loading never completes. Memory is never released

**Expected behavior**
Load successfully and be able to edit (and replace) sounds.

**Screenshots**
![image](https://user-images.githubusercontent.com/13968885/70174665-43cf7e80-16cd-11ea-9e0f-b463093c2333.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v0.30c

**Additional context**
Occasionally the loading does completely successfully, but when trying to save the edited brsar, I get an error saying not enough memory resources are available for this operation.

not entirely sure if I should attach the un-edited brsar for copyright reasons

**Comment by soopercool101** [comment]
If you happen to be on a 64-bit system, please attempt to use the experimental AnyCPU canary build from the releases page, and see if that fixes your issue

**Comment by red031000** [comment]
the brsar opens successfully with that build, but when trying to save the modified (i.e. deleting a folder/replacing a sound) it results in an Arithmatic operation resulted in an overflow.

**Comment by soopercool101** [comment]
Could you post the error here or submit it if it is in the form of a crash log?

**Comment by red031000** [comment]
![image](https://user-images.githubusercontent.com/13968885/70273298-b3af3900-17a1-11ea-824d-f7b9d90e4da0.png)

**Comment by red031000** [comment]
there's not really a whole lot of info provided
