### ISSUE TITLE
Target vertex sets become <null> in SHP0 v4

### ISSUE THREAD

**Issue by strobenz** [soopercool101/BrawlCrate#55]
**Describe the bug**
When creating a version 4 vertex morph (SHP0) entry, any and all target vertex sets become _null_ after saving and reopening the BRRES file. This causes the game to crash (in this case I'm using MKWii)

**To Reproduce**
1. Create an SHP0 entry in a BRRES file, make it v4.
2. Add a new entry to the SHP0 which will create a NewNode and a NewMorphTarget
3. No matter what, the NewMorphTarget will become _null_ after saving and reopening the file with BrawlCrate.
4. Testing the BRRES crashes the game.

**Expected behavior**
The NewMorphTarget should keep the reference to the desired target vertex set.

**Screenshots**
As you can see, the SHP0 is properly set up and BrawlCrate can even show the animation
![image](https://user-images.githubusercontent.com/122639980/212399793-4d152383-2ba4-4fc4-87b6-88f0b870e27e.png)
![image](https://user-images.githubusercontent.com/122639980/212399902-21688630-ad5f-41aa-b830-1cbb325d25de.png)
![image](https://user-images.githubusercontent.com/122639980/212399940-e0f65f78-140c-4c2d-aa32-0f0639dc8ef5.png)
However, upon saving and reopening, the target vertex set (in this case it was called "target") is now _null_
![image](https://user-images.githubusercontent.com/122639980/212400176-def4b0d0-a0bf-45ee-acba-51103025c46d.png)

**Desktop (please complete the following information):**
 - Windows 11
 - BrawlCrate v0.38

**Additional context**
This bug is also present in the last version of BrawlBox, which seems to indicate that it's an old bug that has never been addressed.

[https://drive.google.com/file/d/1MoeNE5NI5TH3Nq99RSyQQwA7qvVnRpDn/view?usp=sharing](Example file)

**Comment by Strobenz** [comment]
So I guess it's true what they say: the current developer does not care about other modding communities that happen to use BrawlCrate. It was quite the opposite 10 years ago when BlackJax96 was around developing BrawlBox, but I suppose times can change for the worse too.

**Comment by soopercool101** [comment]
For the record, I'm busy with things outside of this program, and dedicate my time to it as a hobby. I do in fact want to provide assistance to other modding communities despite Brawl being my primary focus, but I'm just one person lol. Just because I don't have the time to prioritize an issue does not mean it will never be fixed, nor does it mean you have to throw a tantrum after one month of no progress. If you wish to restore the original body of this issue it will allow me to properly address it on my own time, and if you want to pout that is your prerogative as well.

![image](https://user-images.githubusercontent.com/35675593/216845316-dee46944-53f3-41b3-a0c5-c279164b821a.png)

**Comment by strobenz** [comment]
I am sorry for posting such a comment. This is no excuse, but almost at the exact moment when I opened BrawlCrate and it got updated, I got undesirable news about something personal which made me react poorly the way I did. As a fellow modder who also has activities outside of this I completely understand that this is a hobby, and it's not a particularly easy one.

However, and this is something that I need to say, it did seem like this specific issue was being blatantly ignored since I posted a message on the bug reports channel of the official Discord server and it was not given any attention at all. Later messages were at least _responded to_ a lot faster, even if not with an immediate solution to the issues. So I apologize again, but I hope you understand why I thought I was being purposely dismissed.

I will restore the original body, and I will of course be deeply thankful if the issue gets fixed eventually. But I will understand if you decide not to after this situation. Not in a million years would I be able to develop any sort of software, so either way I do thank you for keeping BrawlCrate alive.

**Comment by soopercool101** [comment]
I totally understand, and I appreciate your candidness here. I hope things go better for you and apologize for it seeming like your issue was ignored. I do promise I will look into it deeper when I have the time to do so 👍

**Comment by strobenz** [comment]
Thank you again :)

**Comment by soopercool101** [comment]
Should be fixed in the next Canary build according to my limited tests, you can update to the Canary version by going into your Updater settings in the program. Let me know if this resolves your issue properly and we can close

**Comment by strobenz** [comment]
I tested a few brres files and it does seem like the issue has been fixed. I cannot thank you enough for taking the time to do it precisely today. I still feel bad about earlier, but hopefully we can end in good terms.
