### ISSUE TITLE
U8 Archive folder structure is occasionally saved incorrectly

### ISSUE THREAD

**Issue by Gabriela-Orzechowska** [soopercool101/BrawlCrate#58]
**Describe the bug**
U8 Archive folder structure is occasionally saved incorrectly, which causes crashes in the games.

**Screenshots**
Example: Archive's folder structure of MKWii track got completely destroyed (First file, the second shows how the folders should look like) 
![image](https://user-images.githubusercontent.com/85825993/216847253-cd27fa08-a8ff-4ca9-9766-77c9950d16e2.png)

However the archive looks "correctly" in BrawlCrate itself after saving.
This causes a lot of issues mainly among MKWii creators.

(Additional report) .brasd files do not get names from string pool correctly

**Comment by soopercool101** [comment]
Any chance you (or the rest of the MKWii community) would know of a consistent way to reproduce? Or does it seem purely random?

**Comment by Gabriela-Orzechowska** [comment]
From my today's testing it appears that the issue happens whenever there is more than one nonempty folder in the same location.

**Comment by soopercool101** [comment]
As a followup question, does this only happen with BRASD? I couldn't reproduce on my limited tests but didn't try anything with that filetype in particular

**Comment by Gabriela-Orzechowska** [comment]
Invalid folder structure can happen even without any files inside, just nonempty folders.
Like I mentioned, in Brawlcrate it appears normally, however the game/tools like Wiimm's SZS Tools show that it is in fact incorrect.
I should have reported brasd stuff as separate issue, my bad.

**Comment by soopercool101** [comment]
Could you send a before/after of files saved in such a corrupting fashion? I don't have the time to reproduce at this exact second but I did check with wszst on my earlier tests and was still unable to find anything with the archives I did check

**Comment by Gabriela-Orzechowska** [comment]
[files.zip](https://github.com/soopercool101/BrawlCrate/files/10669428/files.zip)
Here, in the corrupted one I just moved the folders back and forth and saved.
From what im seeing, it's just parent index that is wrong

**Comment by soopercool101** [comment]
Closed as part of #64
