### ISSUE TITLE
Skyward sword HD Texture Loading Issue

### ISSUE THREAD

**Issue by keesoudwater34** [soopercool101/BrawlCrate#85]
**Describe the bug**
Skyward Sword HD files having issue being read.

**To Reproduce**
(Pack extracted from XCI With Hactoolnet)
1. Open the ObjectPack.arc
2. For examle i used Alink.arc. the models seem to load just fine for most of em. But checking the textures a bunch of em are 1 pixel sized or black. Most effect textures  are still in tact.

**Expected behavior**
Textures to be readable.

**Screenshots**
![image](https://github.com/soopercool101/BrawlCrate/assets/50651160/044310c0-44ff-4b4c-ad0a-c49a210af451)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version V0.40a (Occured in older oversions too)

**Additional context**
This is just a guess but i wouldnt be supriced if they added a couple of other texture formats into the files. Either that or the header/footer being different.

Please attach any relevant files you were working on.

[Alink.zip](https://github.com/soopercool101/BrawlCrate/files/13198630/Alink.zip)

**Comment by CovenEsme** [comment]
SSHD decided to change how they "did" textures. In the Wii version of the game, the texture data was bundle in with the BRRES:
![image](https://github.com/soopercool101/BrawlCrate/assets/84377742/81db5938-026b-460c-abd3-7333960c9423)

In HD, there's a new `model.xtx` file that contains all the texture data instead (image from Switch Toolbox):
![image](https://github.com/soopercool101/BrawlCrate/assets/84377742/c5021151-f1b2-4633-89c0-33cfbb64358c)

**Comment by soopercool101** [comment]
I believed this was the case but didn't have SSHD myself to confirm, thanks for the confirmation. Closing
