### ISSUE TITLE
UserEntries no longer shows all entries

### ISSUE THREAD

**Issue by HBroHei** [soopercool101/BrawlCrate#95]
**Describe the bug**
The MDL0 bone node menu no longer shows all entries of the UserEntries.

**To Reproduce**
1. Open a MDL0 (or any file that contains them)
2. Click on any bone in that MDL0 file that has UserEntries
3. Not all entries would be shown in the "UserEntries" section

**Expected behavior**
All Entries should be shown.

**Screenshots**
![brawlcrate_v40a](https://github.com/soopercool101/BrawlCrate/assets/87789469/ad98f340-5706-4232-a7fa-03bfc8ff64de)
Expected behavior (in v40a)
![brawlcrate_v41](https://github.com/soopercool101/BrawlCrate/assets/87789469/f492bbeb-5e13-4e96-9224-195432c4d701)
Observed result (in v41)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2

**Crash Log**
No crash log

**Additional context**
This bug only affects v41 (as of the writing). v40a would still shows all the entries of the bone node.
Tested with .lz encrypted files and non-encrypted files, the result are the same.
File: (Taken from Mario Party 9)
https://drive.google.com/file/d/1-s6RnaTf3FU3iVb0lus5sC8jYqukX0bh/view?usp=drive_link

**Comment by soopercool101** [comment]
Likely a regression from https://github.com/soopercool101/BrawlCrate/commit/b4e08ccd08a9c8de7c59a5da3fc5e4f55b1814ee

Will look into why this would be

**Comment by soopercool101** [comment]
Hopefully your issue will be fixed in the next stable, thank you for bringing this to my attention

**Comment by HBroHei** [comment]
Thank you for the quick response!
