### ISSUE TITLE
There's a virus? Edit - NeverMind, Think its fixed

### ISSUE THREAD

**Issue by LucasD10-m** [soopercool101/BrawlCrate#96]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. v0.30, Canary #e3267f]

**Crash Log**
If there was a crash report, please submit it and include a link to the relevant issue from [BrawlCrateIssues](https://github.com/BrawlCrate/BrawlCrateIssues/issues).

**Additional context**

Please attach any relevant files (if they do not have copyrighted content) you were working on. If the file is from a retail game, please instead name the game and the path to the file in the game's filesystem.

**Comment by soopercool101** [comment]
Microsoft flags unknown files as viruses when they aren't commonly ran, not much I can do from my end on these false positives. If you're worried you can read the source code and build it yourself
