### ISSUE TITLE
Not enough memory resources are available to process this command. (Exception from HRESULT: 0x80070008)

### ISSUE THREAD

**Issue by hunkh** [soopercool101/BrawlCrate#98]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. v0.30, Canary #e3267f]

**Crash Log**
If there was a crash report, please submit it and include a link to the relevant issue from [BrawlCrateIssues](https://github.com/BrawlCrate/BrawlCrateIssues/issues).

**Additional context**

Please attach any relevant files (if they do not have copyrighted content) you were working on. If the file is from a retail game, please instead name the game and the path to the file in the game's filesystem.

**Comment by soopercool101** [comment]
Not enough information
